version: 2
jobs:
  build:
    working_directory: ~/rxfeedback
    docker:
        - image: circleci/android:api-27-alpha
    environment:
        JVM_OPTS: -Xmx3200m
    steps:
          - checkout:
             post:
                - git submodule init
                - git submodule update --init
                - git submodule sync
          - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "rxfeedback/build.gradle" }}
          - run:
              name: Download Dependencies
              command: ./gradlew androidDependencies --debug --stacktrace
          - save_cache:
              paths:
                - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "rxfeedback/build.gradle" }}
          - run:
              name: Run Tests
              command: ./gradlew clean testDebugUnitTest
          - store_artifacts:
              path: rxfeedback/build/reports
              destination: reports
          - store_test_results:
              path: rxfeedback/build/test-results

